export const health = [
    {
        name: 'John Doe',
        email: 'john.doe@example.com',
        allergy: ['Itching', 'Stomach upset', 'Gas'],
        item: ['Milk', 'Cheese', 'Butter'],
    },
    {
        name: 'Alice Smith',
        email: 'alice.smith@example.com',
        allergy: ['Itching', 'Rashes', 'Headache'],
        item: ['Tea', 'Coffee'],
    },
    {
        name: 'Bob Johnson',
        email: 'bob.johnson@example.com',
        allergy: ['Stomach upset', 'Vomiting'],
        item: ['Spicy food', 'Chili'],
    },
    {
        name: 'Emily Davis',
        email: 'emily.davis@example.com',
        allergy: ['Itching', 'Swelling', 'Breathing difficulty'],
        item: ['Peanuts', 'Nuts'],
    },
    {
        name: 'Michael Brown',
        email: 'michael.brown@example.com',
        allergy: ['Gas', 'Bloating'],
        item: ['Cabbage', 'Lentils'],
    },
    {
        name: 'Sarah Wilson',
        email: 'sarah.wilson@example.com',
        allergy: ['Rashes', 'Headache'],
        item: ['Caffeine', 'Chocolate'],
    },
    {
        name: 'David Clark',
        email: 'david.clark@example.com',
        allergy: ['Itching', 'Skin irritation'],
        item: ['Seafood', 'Shellfish'],
    },
    {
        name: 'Laura Adams',
        email: 'laura.adams@example.com',
        allergy: ['Stomach upset', 'Dizziness'],
        item: ['Milk', 'Ice cream'],
    },
    {
        name: 'James Evans',
        email: 'james.evans@example.com',
        allergy: ['Itching', 'Swelling'],
        item: ['Eggs', 'Mayonnaise'],
    },
    {
        name: 'Olivia White',
        email: 'olivia.white@example.com',
        allergy: ['Nausea', 'Breathing difficulty'],
        item: ['Wheat', 'Bread'],
    },
    {
        name: 'Sophia Martinez',
        email: 'sophia.martinez@example.com',
        allergy: ['Itching', 'Swelling'],
        item: ['Honey', 'Pollen'],
    },
    {
        name: 'Jack Robinson',
        email: 'jack.robinson@example.com',
        allergy: ['Nausea', 'Dizziness'],
        item: ['Shellfish', 'Lobster'],
    },
    {
        name: 'Lily Harris',
        email: 'lily.harris@example.com',
        allergy: ['Itching', 'Headache'],
        item: ['Cheese', 'Yogurt'],
    },
    {
        name: 'Oliver Walker',
        email: 'oliver.walker@example.com',
        allergy: ['Gas', 'Bloating'],
        item: ['Beans', 'Broccoli'],
    },
    {
        name: 'Charlotte Scott',
        email: 'charlotte.scott@example.com',
        allergy: ['Stomach upset', 'Diarrhea'],
        item: ['Chocolate', 'Caffeine'],
    },
    {
        name: 'Lucas Allen',
        email: 'lucas.allen@example.com',
        allergy: ['Itching', 'Skin irritation'],
        item: ['Fish', 'Shrimp'],
    },
    {
        name: 'Grace Young',
        email: 'grace.young@example.com',
        allergy: ['Rashes', 'Breathing difficulty'],
        item: ['Pineapple', 'Papaya'],
    },
    {
        name: 'Ethan King',
        email: 'ethan.king@example.com',
        allergy: ['Stomach upset', 'Vomiting'],
        item: ['Citrus fruits', 'Oranges'],
    },
    {
        name: 'Isabella Lee',
        email: 'isabella.lee@example.com',
        allergy: ['Itching', 'Swelling'],
        item: ['Nuts', 'Almonds'],
    },
    {
        name: 'Mason Perez',
        email: 'mason.perez@example.com',
        allergy: ['Gas', 'Bloating'],
        item: ['Cabbage', 'Cauliflower'],
    },
    {
        name: 'Chloe Harris',
        email: 'chloe.harris@example.com',
        allergy: ['Itching', 'Headache'],
        item: ['Coffee', 'Tea'],
    },
    {
        name: 'Aiden Robinson',
        email: 'aiden.robinson@example.com',
        allergy: ['Itching', 'Stomach upset'],
        item: ['Chocolate', 'Peanuts'],
    },
    {
        name: 'Mia Clark',
        email: 'mia.clark@example.com',
        allergy: ['Rashes', 'Swelling'],
        item: ['Eggs', 'Dairy'],
    },
    {
        name: 'Sebastian Evans',
        email: 'sebastian.evans@example.com',
        allergy: ['Nausea', 'Dizziness'],
        item: ['Caffeine', 'Tea'],
    },
    {
        name: 'Amelia White',
        email: 'amelia.white@example.com',
        allergy: ['Stomach upset', 'Diarrhea'],
        item: ['Tomatoes', 'Chili'],
    },
    {
        name: 'Benjamin King',
        email: 'benjamin.king@example.com',
        allergy: ['Itching', 'Stomach upset'],
        item: ['Soy', 'Tofu'],
    },
    {
        name: 'Harper Allen',
        email: 'harper.allen@example.com',
        allergy: ['Gas', 'Bloating'],
        item: ['Lentils', 'Chickpeas'],
    },
    {
        name: 'Liam Carter',
        email: 'liam.carter@example.com',
        allergy: ['Itching', 'Rashes'],
        item: ['Mango', 'Papaya'],
    },
    {
        name: 'Zoe Perez',
        email: 'zoe.perez@example.com',
        allergy: ['Headache', 'Nausea'],
        item: ['Alcohol', 'Wine'],
    },
    {
        name: 'Henry Turner',
        email: 'henry.turner@example.com',
        allergy: ['Itching', 'Swelling'],
        item: ['Shellfish', 'Crab'],
    },
    {
        name: 'Ella Mitchell',
        email: 'ella.mitchell@example.com',
        allergy: ['Stomach upset', 'Vomiting'],
        item: ['Spicy foods', 'Chili'],
    },
    {
        name: 'Jack Thomas',
        email: 'jack.thomas@example.com',
        allergy: ['Gas', 'Bloating'],
        item: ['Onions', 'Garlic'],
    },
    {
        name: 'Avery Walker',
        email: 'avery.walker@example.com',
        allergy: ['Itching', 'Skin irritation'],
        item: ['Tomatoes', 'Peppers'],
    },
    {
        name: 'Levi Harris',
        email: 'levi.harris@example.com',
        allergy: ['Nausea', 'Vomiting'],
        item: ['Shellfish', 'Lobster'],
    },
    {
        name: 'Maya Young',
        email: 'maya.young@example.com',
        allergy: ['Rashes', 'Swelling'],
        item: ['Citrus fruits', 'Oranges'],
    },
    {
        name: 'Owen Scott',
        email: 'owen.scott@example.com',
        allergy: ['Itching', 'Stomach upset'],
        item: ['Dairy', 'Cheese'],
    },
    {
        name: 'Madeline Clark',
        email: 'madeline.clark@example.com',
        allergy: ['Gas', 'Bloating'],
        item: ['Brussels sprouts', 'Cabbage'],
    },
    {
        name: 'Eli Moore',
        email: 'eli.moore@example.com',
        allergy: ['Headache', 'Rashes'],
        item: ['Caffeine', 'Chocolate'],
    },
    {
        name: 'Charlotte Lee',
        email: 'charlotte.lee@example.com',
        allergy: ['Itching', 'Stomach upset'],
        item: ['Milk', 'Butter'],
    },
    {
        name: 'Isaiah Davis',
        email: 'isaiah.davis@example.com',
        allergy: ['Itching', 'Rashes'],
        item: ['Pineapple', 'Strawberries'],
    },
    {
        name: 'Chloe Taylor',
        email: 'chloe.taylor@example.com',
        allergy: ['Breathing difficulty', 'Coughing'],
        item: ['Eggs', 'Dairy'],
    },
    {
        name: 'Aaron Wilson',
        email: 'aaron.wilson@example.com',
        allergy: ['Stomach upset', 'Diarrhea'],
        item: ['Onions', 'Garlic'],
    },
    {
        name: 'Savannah Robinson',
        email: 'savannah.robinson@example.com',
        allergy: ['Nausea', 'Dizziness'],
        item: ['Alcohol', 'Beer'],
    },
    {
        name: 'Cameron Harris',
        email: 'cameron.harris@example.com',
        allergy: ['Itching', 'Swelling'],
        item: ['Seafood', 'Fish'],
    },
    {
        name: 'Megan King',
        email: 'megan.king@example.com',
        allergy: ['Rashes', 'Itching'],
        item: ['Nuts', 'Peanuts'],
    },
    {
        name: 'Nathaniel Wright',
        email: 'nathaniel.wright@example.com',
        allergy: ['Stomach upset', 'Vomiting'],
        item: ['Chili', 'Spicy foods'],
    },
    {
        name: 'Olivia Bennett',
        email: 'olivia.bennett@example.com',
        allergy: ['Itching', 'Nausea'],
        item: ['Chocolate', 'Ice cream'],
    },
];
