export const health = [
    {
        name: 'John Doe',
        email: 'john.doe@example.com',
        allergy: ['Itching', 'Stomach upset', 'Gas'],
        item: ['Milk', 'Cheese', 'Butter'],
    },
    {
        name: 'Alice Smith',
        email: 'alice.smith@example.com',
        allergy: ['Itching', 'Rashes', 'Headache'],
        item: ['Tea', 'Coffee'],
    },
    {
        name: 'Bob Johnson',
        email: 'bob.johnson@example.com',
        allergy: ['Stomach upset', 'Vomiting'],
        item: ['Spicy food', 'Chili'],
    },
    {
        name: 'Emily Davis',
        email: 'emily.davis@example.com',
        allergy: ['Itching', 'Swelling', 'Breathing difficulty'],
        item: ['Peanuts', 'Nuts'],
    },
    {
        name: 'Michael Brown',
        email: 'michael.brown@example.com',
        allergy: ['Gas', 'Bloating'],
        item: ['Cabbage', 'Lentils'],
    },
    {
        name: 'Sarah Wilson',
        email: 'sarah.wilson@example.com',
        allergy: ['Rashes', 'Headache'],
        item: ['Caffeine', 'Chocolate'],
    },
    {
        name: 'David Clark',
        email: 'david.clark@example.com',
        allergy: ['Itching', 'Skin irritation'],
        item: ['Seafood', 'Shellfish'],
    },
    {
        name: 'Laura Adams',
        email: 'laura.adams@example.com',
        allergy: ['Stomach upset', 'Dizziness'],
        item: ['Milk', 'Ice cream'],
    },
    {
        name: 'James Evans',
        email: 'james.evans@example.com',
        allergy: ['Itching', 'Swelling'],
        item: ['Eggs', 'Mayonnaise'],
    },
    {
        name: 'Olivia White',
        email: 'olivia.white@example.com',
        allergy: ['Nausea', 'Breathing difficulty'],
        item: ['Wheat', 'Bread'],
    },
    {
        name: 'Sophia Martinez',
        email: 'sophia.martinez@example.com',
        allergy: ['Itching', 'Swelling'],
        item: ['Honey', 'Pollen'],
    },
    {
        name: 'Jack Robinson',
        email: 'jack.robinson@example.com',
        allergy: ['Nausea', 'Dizziness'],
        item: ['Shellfish', 'Lobster'],
    },
    {
        name: 'Lily Harris',
        email: 'lily.harris@example.com',
        allergy: ['Itching', 'Headache'],
        item: ['Cheese', 'Yogurt'],
    },
    {
        name: 'Oliver Walker',
        email: 'oliver.walker@example.com',
        allergy: ['Gas', 'Bloating'],
        item: ['Beans', 'Broccoli'],
    },
    {
        name: 'Charlotte Scott',
        email: 'charlotte.scott@example.com',
        allergy: ['Stomach upset', 'Diarrhea'],
        item: ['Chocolate', 'Caffeine'],
    },
    {
        name: 'Lucas Allen',
        email: 'lucas.allen@example.com',
        allergy: ['Itching', 'Skin irritation'],
        item: ['Fish', 'Shrimp'],
    },
    {
        name: 'Grace Young',
        email: 'grace.young@example.com',
        allergy: ['Rashes', 'Breathing difficulty'],
        item: ['Pineapple', 'Papaya'],
    },
    {
        name: 'Ethan King',
        email: 'ethan.king@example.com',
        allergy: ['Stomach upset', 'Vomiting'],
        item: ['Citrus fruits', 'Oranges'],
    },
    {
        name: 'Isabella Lee',
        email: 'isabella.lee@example.com',
        allergy: ['Itching', 'Swelling'],
        item: ['Nuts', 'Almonds'],
    },
    {
        name: 'Mason Perez',
        email: 'mason.perez@example.com',
        allergy: ['Gas', 'Bloating'],
        item: ['Cabbage', 'Cauliflower'],
    },
    {
        name: 'Chloe Harris',
        email: 'chloe.harris@example.com',
        allergy: ['Itching', 'Headache'],
        item: ['Coffee', 'Tea'],
    },
    {
        name: 'Aiden Robinson',
        email: 'aiden.robinson@example.com',
        allergy: ['Itching', 'Stomach upset'],
        item: ['Chocolate', 'Peanuts'],
    },
    {
        name: 'Mia Clark',
        email: 'mia.clark@example.com',
        allergy: ['Rashes', 'Swelling'],
        item: ['Eggs', 'Dairy'],
    },
    {
        name: 'Sebastian Evans',
        email: 'sebastian.evans@example.com',
        allergy: ['Nausea', 'Dizziness'],
        item: ['Caffeine', 'Tea'],
    },
    {
        name: 'Amelia White',
        email: 'amelia.white@example.com',
        allergy: ['Stomach upset', 'Diarrhea'],
        item: ['Tomatoes', 'Chili'],
    },
    {
        name: 'Benjamin King',
        email: 'benjamin.king@example.com',
        allergy: ['Itching', 'Stomach upset'],
        item: ['Soy', 'Tofu'],
    },
    {
        name: 'Harper Allen',
        email: 'harper.allen@example.com',
        allergy: ['Gas', 'Bloating'],
        item: ['Lentils', 'Chickpeas'],
    },
    {
        name: 'Liam Carter',
        email: 'liam.carter@example.com',
        allergy: ['Itching', 'Rashes'],
        item: ['Mango', 'Papaya'],
    },
    {
        name: 'Zoe Perez',
        email: 'zoe.perez@example.com',
        allergy: ['Headache', 'Nausea'],
        item: ['Alcohol', 'Wine'],
    },
    {
        name: 'Henry Turner',
        email: 'henry.turner@example.com',
        allergy: ['Itching', 'Swelling'],
        item: ['Shellfish', 'Crab'],
    },
    {
        name: 'Ella Mitchell',
        email: 'ella.mitchell@example.com',
        allergy: ['Stomach upset', 'Vomiting'],
        item: ['Spicy foods', 'Chili'],
    },
    {
        name: 'Jack Thomas',
        email: 'jack.thomas@example.com',
        allergy: ['Gas', 'Bloating'],
        item: ['Onions', 'Garlic'],
    },
    {
        name: 'Avery Walker',
        email: 'avery.walker@example.com',
        allergy: ['Itching', 'Skin irritation'],
        item: ['Tomatoes', 'Peppers'],
    },
    {
        name: 'Levi Harris',
        email: 'levi.harris@example.com',
        allergy: ['Nausea', 'Vomiting'],
        item: ['Shellfish', 'Lobster'],
    },
    {
        name: 'Maya Young',
        email: 'maya.young@example.com',
        allergy: ['Rashes', 'Swelling'],
        item: ['Citrus fruits', 'Oranges'],
    },
    {
        name: 'Owen Scott',
        email: 'owen.scott@example.com',
        allergy: ['Itching', 'Stomach upset'],
        item: ['Dairy', 'Cheese'],
    },
    {
        name: 'Madeline Clark',
        email: 'madeline.clark@example.com',
        allergy: ['Gas', 'Bloating'],
        item: ['Brussels sprouts', 'Cabbage'],
    },
    {
        name: 'Eli Moore',
        email: 'eli.moore@example.com',
        allergy: ['Headache', 'Rashes'],
        item: ['Caffeine', 'Chocolate'],
    },
    {
        name: 'Charlotte Lee',
        email: 'charlotte.lee@example.com',
        allergy: ['Itching', 'Stomach upset'],
        item: ['Milk', 'Butter'],
    },
    {
        name: 'Isaiah Davis',
        email: 'isaiah.davis@example.com',
        allergy: ['Itching', 'Rashes'],
        item: ['Pineapple', 'Strawberries'],
    },
    {
        name: 'Chloe Taylor',
        email: 'chloe.taylor@example.com',
        allergy: ['Breathing difficulty', 'Coughing'],
        item: ['Eggs', 'Dairy'],
    },
    {
        name: 'Aaron Wilson',
        email: 'aaron.wilson@example.com',
        allergy: ['Stomach upset', 'Diarrhea'],
        item: ['Onions', 'Garlic'],
    },
    {
        name: 'Savannah Robinson',
        email: 'savannah.robinson@example.com',
        allergy: ['Nausea', 'Dizziness'],
        item: ['Alcohol', 'Beer'],
    },
    {
        name: 'Cameron Harris',
        email: 'cameron.harris@example.com',
        allergy: ['Itching', 'Swelling'],
        item: ['Seafood', 'Fish'],
    },
    {
        name: 'Megan King',
        email: 'megan.king@example.com',
        allergy: ['Rashes', 'Itching'],
        item: ['Nuts', 'Peanuts'],
    },
    {
        name: 'Nathaniel Wright',
        email: 'nathaniel.wright@example.com',
        allergy: ['Stomach upset', 'Vomiting'],
        item: ['Chili', 'Spicy foods'],
    },
    {
        name: 'Olivia Bennett',
        email: 'olivia.bennett@example.com',
        allergy: ['Itching', 'Nausea'],
        item: ['Chocolate', 'Ice cream'],
    },
];


export const health2 = [
    {
        name: 'Olivia Young',
        email: 'olivia.young@example.com',
        allergy: ['Itching', 'Rashes'],
        item: ['Citrus', 'Lemon'],
    },
    {
        name: 'Ethan Hernandez',
        email: 'ethan.hernandez@example.com',
        allergy: ['Stomach upset'],
        item: ['Fried Foods', 'Fatty Foods'],
    },
    {
        name: 'Ava King',
        email: 'ava.king@example.com',
        allergy: ['Itching', 'Rashes'],
        item: ['Cherries', 'Pineapple'],
    },
    {
        name: 'Mason Scott',
        email: 'mason.scott@example.com',
        allergy: ['Nausea', 'Vomiting'],
        item: ['Seafood', 'Shrimp'],
    },
    {
        name: 'Isabella Green',
        email: 'isabella.green@example.com',
        allergy: ['Itching', 'Cough'],
        item: ['Air Fresheners', 'Perfumes'],
    },
    {
        name: 'Alexander Adams',
        email: 'alexander.adams@example.com',
        allergy: ['Rashes'],
        item: ['Coconut', 'Peanut Butter'],
    },
    {
        name: 'John Doe',
        email: 'john.doe@example.com',
        allergy: ['Itching', 'Stomach upset', 'Gas'],
        item: ['Milk', 'Cheese', 'Butter'],
    },
    {
        name: 'Alice Smith',
        email: 'alice.smith@example.com',
        allergy: ['Itching', 'Rashes', 'Headache'],
        item: ['Tea', 'Coffee'],
    },
    {
        name: 'Bob Johnson',
        email: 'bob.johnson@example.com',
        allergy: ['Itching', 'Nausea'],
        item: ['Peanuts', 'Almonds'],
    },
    {
        name: 'Sarah Williams',
        email: 'sarah.williams@example.com',
        allergy: ['Sneezing', 'Cough'],
        item: ['Dust', 'Pollen'],
    },
    {
        name: 'David Brown',
        email: 'david.brown@example.com',
        allergy: ['Rashes', 'Headache'],
        item: ['Chocolate', 'Peanut Butter'],
    },
    {
        name: 'Emily Davis',
        email: 'emily.davis@example.com',
        allergy: ['Itching', 'Stomach upset'],
        item: ['Eggs', 'Cheese'],
    },
    {
        name: 'Michael Miller',
        email: 'michael.miller@example.com',
        allergy: ['Sneezing', 'Itching'],
        item: ['Pollen', 'Pet Dander'],
    },
    {
        name: 'Linda Taylor',
        email: 'linda.taylor@example.com',
        allergy: ['Nausea', 'Vomiting'],
        item: ['Shellfish', 'Lobster'],
    },
    {
        name: 'James Anderson',
        email: 'james.anderson@example.com',
        allergy: ['Itching'],
        item: ['Tomatoes', 'Cherries'],
    },
    {
        name: 'Patricia Thomas',
        email: 'patricia.thomas@example.com',
        allergy: ['Rashes', 'Stomach upset'],
        item: ['Gluten', 'Wheat'],
    },
    {
        name: 'Daniel Martinez',
        email: 'daniel.martinez@example.com',
        allergy: ['Headache', 'Nausea'],
        item: ['Citrus', 'Oranges'],
    },
    {
        name: 'Susan Garcia',
        email: 'susan.garcia@example.com',
        allergy: ['Itching', 'Rashes'],
        item: ['Peanuts', 'Milk'],
    },
    {
        name: 'Robert Rodriguez',
        email: 'robert.rodriguez@example.com',
        allergy: ['Stomach upset'],
        item: ['Dairy', 'Chocolate'],
    },
    {
        name: 'Jessica Lee',
        email: 'jessica.lee@example.com',
        allergy: ['Itching', 'Cough'],
        item: ['Dust', 'Pollen'],
    },
    {
        name: 'William Walker',
        email: 'william.walker@example.com',
        allergy: ['Rashes'],
        item: ['Soy', 'Wheat'],
    },
    {
        name: 'Sophia Hall',
        email: 'sophia.hall@example.com',
        allergy: ['Headache', 'Nausea'],
        item: ['Cheese', 'Milk'],
    },
    {
        name: 'Henry Allen',
        email: 'henry.allen@example.com',
        allergy: ['Sneezing'],
        item: ['Pet Dander'],
    },
    {
        name: 'Olivia Young',
        email: 'olivia.young@example.com',
        allergy: ['Itching', 'Rashes'],
        item: ['Citrus', 'Lemon'],
    },
    {
        name: 'Ethan Hernandez',
        email: 'ethan.hernandez@example.com',
        allergy: ['Stomach upset'],
        item: ['Fried Foods', 'Fatty Foods'],
    },
    {
        name: 'Ava King',
        email: 'ava.king@example.com',
        allergy: ['Itching', 'Rashes'],
        item: ['Cherries', 'Pineapple'],
    },
    {
        name: 'Mason Scott',
        email: 'mason.scott@example.com',
        allergy: ['Nausea', 'Vomiting'],
        item: ['Seafood', 'Shrimp'],
    },
    {
        name: 'Isabella Green',
        email: 'isabella.green@example.com',
        allergy: ['Itching', 'Cough'],
        item: ['Air Fresheners', 'Perfumes'],
    },
    {
        name: 'Alexander Adams',
        email: 'alexander.adams@example.com',
        allergy: ['Rashes'],
        item: ['Coconut', 'Peanut Butter'],
    },
    {
        name: 'Charlotte Nelson',
        email: 'charlotte.nelson@example.com',
        allergy: ['Headache'],
        item: ['Alcohol', 'Caffeine'],
    },
    {
        name: 'Sebastian Carter',
        email: 'sebastian.carter@example.com',
        allergy: ['Nausea', 'Rashes'],
        item: ['Gluten', 'Bread'],
    },
    {
        name: 'Amelia Mitchell',
        email: 'amelia.mitchell@example.com',
        allergy: ['Itching'],
        item: ['Milk', 'Dairy'],
    },
    {
        name: 'Jack Perez',
        email: 'jack.perez@example.com',
        allergy: ['Headache'],
        item: ['Chocolate', 'Sugar'],
    },
    {
        name: 'Mia Roberts',
        email: 'mia.roberts@example.com',
        allergy: ['Itching', 'Rashes'],
        item: ['Strawberries', 'Tomatoes'],
    },
    {
        name: 'Benjamin Clark',
        email: 'benjamin.clark@example.com',
        allergy: ['Sneezing'],
        item: ['Dust', 'Mold'],
    },
    {
        name: 'Eleanor Lewis',
        email: 'eleanor.lewis@example.com',
        allergy: ['Rashes'],
        item: ['Fruits', 'Peaches'],
    },
    {
        name: 'Lucas Lee',
        email: 'lucas.lee@example.com',
        allergy: ['Stomach upset'],
        item: ['Fast Food', 'Pizza'],
    },
    {
        name: 'Harper Walker',
        email: 'harper.walker@example.com',
        allergy: ['Nausea'],
        item: ['Peppers', 'Spices'],
    },
    {
        name: 'Henry Moore',
        email: 'henry.moore@example.com',
        allergy: ['Itching'],
        item: ['Pet Dander'],
    },
    {
        name: 'Scarlett Hall',
        email: 'scarlett.hall@example.com',
        allergy: ['Rashes'],
        item: ['Milk', 'Cheese'],
    },
    {
        name: 'Samuel Allen',
        email: 'samuel.allen@example.com',
        allergy: ['Headache'],
        item: ['Red Wine', 'Coffee'],
    },
    {
        name: 'Avery Young',
        email: 'avery.young@example.com',
        allergy: ['Stomach upset'],
        item: ['Citrus', 'Lemon'],
    },
    {
        name: 'Matthew Walker',
        email: 'matthew.walker@example.com',
        allergy: ['Nausea'],
        item: ['Fried Chicken', 'Onions'],
    },
    {
        name: 'Sofia Lewis',
        email: 'sofia.lewis@example.com',
        allergy: ['Itching', 'Rashes'],
        item: ['Shellfish', 'Crab'],
    },
    {
        name: 'Joseph Moore',
        email: 'joseph.moore@example.com',
        allergy: ['Rashes'],
        item: ['Avocado', 'Nuts'],
    },
    {
        name: 'Ella Martin',
        email: 'ella.martin@example.com',
        allergy: ['Headache', 'Itching'],
        item: ['Coffee', 'Chocolate'],
    },
];

export const health3 = [
    {
        name: 'Mark Nelson',
        email: 'mark.nelson@example.com',
        allergy: ['Hives', 'Swelling'],
        item: ['Sesame'],
    },
    {
        name: 'Susan Hall',
        email: 'susan.hall@example.com',
        allergy: ['Sneezing', 'Itching'],
        item: ['Trees'],
    },
    {
        name: 'Steven Young',
        email: 'steven.young@example.com',
        allergy: ['Nausea', 'Vomiting'],
        item: ['Shellfish'],
    },
    {
        name: 'Donna King',
        email: 'donna.king@example.com',
        allergy: ['Itching', 'Rashes'],
        item: ['Aspirin'],
    },
    {
        name: 'Andrew Wright',
        email: 'andrew.wright@example.com',
        allergy: ['Coughing', 'Wheezing'],
        item: ['Dust Mites'],
    },
    {
        name: 'Deborah Perez',
        email: 'deborah.perez@example.com',
        allergy: ['Hives', 'Swelling'],
        item: ['Kiwi'],
    },
    {
        name: 'John Doe',
        email: 'john.doe@example.com',
        allergy: ['Itching', 'Stomach upset', 'Gas'],
        item: ['Milk', 'Cheese', 'Butter'],
    },
    {
        name: 'Alice Smith',
        email: 'alice.smith@example.com',
        allergy: ['Itching', 'Rashes', 'Headache'],
        item: ['Tea', 'Coffee'],
    },
    {
        name: 'Robert Brown',
        email: 'robert.brown@example.com',
        allergy: ['Sneezing', 'Congestion'],
        item: ['Pollen', 'Dust'],
    },
    {
        name: 'Emily Davis',
        email: 'emily.davis@example.com',
        allergy: ['Nausea', 'Vomiting'],
        item: ['Shellfish'],
    },
    {
        name: 'Michael Johnson',
        email: 'michael.johnson@example.com',
        allergy: ['Hives', 'Swelling'],
        item: ['Peanuts'],
    },
    {
        name: 'Jessica Wilson',
        email: 'jessica.wilson@example.com',
        allergy: ['Itching', 'Redness'],
        item: ['Latex'],
    },
    {
        name: 'David Martinez',
        email: 'david.martinez@example.com',
        allergy: ['Coughing', 'Wheezing'],
        item: ['Pet Dander'],
    },
    {
        name: 'Sarah Lee',
        email: 'sarah.lee@example.com',
        allergy: ['Rashes', 'Itching'],
        item: ['Strawberries'],
    },
    {
        name: 'Daniel White',
        email: 'daniel.white@example.com',
        allergy: ['Nausea', 'Stomach pain'],
        item: ['Gluten'],
    },
    {
        name: 'Laura Thompson',
        email: 'laura.thompson@example.com',
        allergy: ['Hives', 'Swelling'],
        item: ['Eggs'],
    },
    {
        name: 'James Anderson',
        email: 'james.anderson@example.com',
        allergy: ['Sneezing', 'Congestion'],
        item: ['Grass'],
    },
    {
        name: 'Patricia Thomas',
        email: 'patricia.thomas@example.com',
        allergy: ['Headache', 'Nausea'],
        item: ['Wine'],
    },
    {
        name: 'Charles Harris',
        email: 'charles.harris@example.com',
        allergy: ['Itching', 'Redness'],
        item: ['Perfume'],
    },
    {
        name: 'Karen Martinez',
        email: 'karen.martinez@example.com',
        allergy: ['Coughing', 'Wheezing'],
        item: ['Mold'],
    },
    {
        name: 'Anthony Clark',
        email: 'anthony.clark@example.com',
        allergy: ['Hives', 'Swelling'],
        item: ['Soy'],
    },
    {
        name: 'Barbara Jackson',
        email: 'barbara.jackson@example.com',
        allergy: ['Sneezing', 'Itching'],
        item: ['Cats'],
    },
    {
        name: 'Christopher Scott',
        email: 'christopher.scott@example.com',
        allergy: ['Nausea', 'Vomiting'],
        item: ['Fish'],
    },
    {
        name: 'Nancy Lewis',
        email: 'nancy.lewis@example.com',
        allergy: ['Itching', 'Rashes'],
        item: ['Detergents'],
    },
    {
        name: 'Brian Walker',
        email: 'brian.walker@example.com',
        allergy: ['Coughing', 'Wheezing'],
        item: ['Smoke'],
    },
    {
        name: 'Margaret Robinson',
        email: 'margaret.robinson@example.com',
        allergy: ['Hives', 'Swelling'],
        item: ['Wheat'],
    },
    {
        name: 'Jason Green',
        email: 'jason.green@example.com',
        allergy: ['Sneezing', 'Congestion'],
        item: ['Ragweed'],
    },
    {
        name: 'Linda Adams',
        email: 'linda.adams@example.com',
        allergy: ['Headache', 'Nausea'],
        item: ['MSG'],
    },
    {
        name: 'Paul Baker',
        email: 'paul.baker@example.com',
        allergy: ['Itching', 'Redness'],
        item: ['Nickel'],
    },
    {
        name: 'Elizabeth Gonzalez',
        email: 'elizabeth.gonzalez@example.com',
        allergy: ['Coughing', 'Wheezing'],
        item: ['Dander'],
    },
    {
        name: 'Mark Nelson',
        email: 'mark.nelson@example.com',
        allergy: ['Hives', 'Swelling'],
        item: ['Sesame'],
    },
    {
        name: 'Susan Hall',
        email: 'susan.hall@example.com',
        allergy: ['Sneezing', 'Itching'],
        item: ['Trees'],
    },
    {
        name: 'Steven Young',
        email: 'steven.young@example.com',
        allergy: ['Nausea', 'Vomiting'],
        item: ['Shellfish'],
    },
    {
        name: 'Donna King',
        email: 'donna.king@example.com',
        allergy: ['Itching', 'Rashes'],
        item: ['Aspirin'],
    },
    {
        name: 'Andrew Wright',
        email: 'andrew.wright@example.com',
        allergy: ['Coughing', 'Wheezing'],
        item: ['Dust Mites'],
    },
    {
        name: 'Deborah Perez',
        email: 'deborah.perez@example.com',
        allergy: ['Hives', 'Swelling'],
        item: ['Kiwi'],
    },
    {
        name: 'Kenneth Wood',
        email: 'kenneth.wood@example.com',
        allergy: ['Sneezing', 'Congestion'],
        item: ['Bermuda Grass'],
    },
    {
        name: 'Linda Sanchez',
        email: 'linda.sanchez@example.com',
        allergy: ['Headache', 'Nausea'],
        item: ['Tyramine'],
    },
    {
        name: 'Matthew Fisher',
        email: 'matthew.fisher@example.com',
        allergy: ['Itching', 'Redness'],
        item: ['Cinnamon'],
    },
    {
        name: 'Lisa Morris',
        email: 'lisa.morris@example.com',
        allergy: ['Coughing', 'Wheezing'],
        item: ['Cockroaches'],
    },
    {
        name: 'Joshua Rogers',
        email: 'joshua.rogers@example.com',
        allergy: ['Hives', 'Swelling'],
        item: ['Barley'],
    },
    {
        name: 'Rebecca Bell',
        email: 'rebecca.bell@example.com',
        allergy: ['Sneezing', 'Itching'],
        item: ['Oak Trees'],
    },
    {
        name: 'John Bennett',
        email: 'john.bennett@example.com',
        allergy: ['Nausea', 'Vomiting'],
        item: ['Octopus'],
    },
    {
        name: 'Kathleen Cooper',
        email: 'kathleen.cooper@example.com',
        allergy: ['Itching', 'Rashes'],
        item: ['Aspirin'],
    },
    {
        name: 'Ryan Bailey',
        email: 'ryan.bailey@example.com',
        allergy: ['Coughing', 'Wheezing'],
        item: ['Animal Hair'],
    },
    {
        name: 'Sharon Reed',
        email: 'sharon.reed@example.com',
        allergy: ['Hives', 'Swelling'],
        item: ['Apples'],
    },
];
