export const overView = [
    {
        user: { email: 'john@example.com', name: 'John' },
        dishes: ['Caesar Salad', 'Naan', 'Cheesecake'],
        tableNumber: 1,
        date: '2023-10-01',
    },
    {
        user: { email: 'jane@example.com', name: 'Jane' },
        dishes: ['Grilled Salmon', 'Naan', 'Syrup'],
        tableNumber: 2,
        date: '2023-10-02',
    },
    {
        user: { email: 'alice@example.com', name: 'Alice' },
        dishes: ['Beef Steak', 'Burger', 'Steak Sandwich'],
        tableNumber: 3,
        date: '2023-10-03',
    },
    {
        user: { email: 'bob@example.com', name: 'Bob' },
        dishes: ['Caesar Salad', 'Grilled Salmon', 'Pancakes', 'Syrup'],
        tableNumber: 4,
        date: '2023-10-04',
    },
    {
        user: { email: 'charlie@example.com', name: 'Charlie' },
        dishes: ['Naan', 'Burger', 'Cheesecake'],
        tableNumber: 5,
        date: '2023-10-05',
    },
    {
        user: { email: 'emma@example.com', name: 'Emma' },
        dishes: ['Caesar Salad'],
        tableNumber: 6,
        date: '2023-10-06',
    },
    {
        user: { email: 'michael@example.com', name: 'Michael' },
        dishes: ['Grilled Salmon', 'Beef Steak'],
        tableNumber: 7,
        date: '2023-10-07',
    },
    {
        user: { email: 'sophia@example.com', name: 'Sophia' },
        dishes: ['Burger', 'Naan', 'Steak Sandwich'],
        tableNumber: 8,
        date: '2023-10-08',
    },
    {
        user: { email: 'william@example.com', name: 'William' },
        dishes: ['Sushi', 'Naan', 'Burrito'],
        tableNumber: 9,
        date: '2023-10-09',
    },
    {
        user: { email: 'olivia@example.com', name: 'Olivia' },
        dishes: ['Caesar Salad', 'Burrito', 'Cheesecake'],
        tableNumber: 10,
        date: '2023-10-10',
    },
    {
        user: { email: 'james@example.com', name: 'James' },
        dishes: ['Grilled Salmon', 'Naan', 'Ramen', 'Cheesecake'],
        tableNumber: 11,
        date: '2023-10-11',
    },
    {
        user: { email: 'amelia@example.com', name: 'Amelia' },
        dishes: ['Beef Steak', 'Burger'],
        tableNumber: 12,
        date: '2023-10-12',
    },
    {
        user: { email: 'benjamin@example.com', name: 'Benjamin' },
        dishes: ['Caesar Salad', 'Naan', 'Ramen'],
        tableNumber: 13,
        date: '2023-10-13',
    },
    {
        user: { email: 'mia@example.com', name: 'Mia' },
        dishes: ['Sushi', 'Caesar Salad'],
        tableNumber: 14,
        date: '2023-10-14',
    },
    {
        user: { email: 'ethan@example.com', name: 'Ethan' },
        dishes: ['Grilled Salmon', 'Beef Steak', 'Ramen'],
        tableNumber: 15,
        date: '2023-10-15',
    },
];

export const overView2 = [
    {
        user: { email: 'john@example.com', name: 'John' },
        dishes: ['Caesar Salad', 'Naan', 'Cheesecake'],
        tableNumber: 1,
        date: '2023-10-01',
    },
    {
        user: { email: 'jane@example.com', name: 'Jane' },
        dishes: ['Grilled Salmon', 'Naan', 'Syrup'],
        tableNumber: 2,
        date: '2023-10-02',
    },
    {
        user: { email: 'alice@example.com', name: 'Alice' },
        dishes: ['Beef Steak', 'Burger', 'Steak Sandwich'],
        tableNumber: 3,
        date: '2023-10-03',
    },
    {
        user: { email: 'bob@example.com', name: 'Bob' },
        dishes: ['Pizza', 'Garlic Bread', 'Ice Cream'],
        tableNumber: 4,
        date: '2023-10-04',
    },
    {
        user: { email: 'emma@example.com', name: 'Emma' },
        dishes: ['Pasta', 'Bruschetta', 'Tiramisu'],
        tableNumber: 5,
        date: '2023-10-05',
    },
    {
        user: { email: 'michael@example.com', name: 'Michael' },
        dishes: ['Sushi', 'Miso Soup', 'Green Tea Ice Cream'],
        tableNumber: 6,
        date: '2023-10-06',
    },
    {
        user: { email: 'sarah@example.com', name: 'Sarah' },
        dishes: ['Tacos', 'Guacamole', 'Churros'],
        tableNumber: 7,
        date: '2023-10-07',
    },
    {
        user: { email: 'david@example.com', name: 'David' },
        dishes: ['Burger', 'Fries', 'Milkshake'],
        tableNumber: 8,
        date: '2023-10-08',
    },
    {
        user: { email: 'linda@example.com', name: 'Linda' },
        dishes: ['Fried Chicken', 'Mashed Potatoes', 'Coleslaw'],
        tableNumber: 9,
        date: '2023-10-09',
    },
    {
        user: { email: 'james@example.com', name: 'James' },
        dishes: ['Ramen', 'Gyoza', 'Matcha Ice Cream'],
        tableNumber: 10,
        date: '2023-10-10',
    },
    {
        user: { email: 'olivia@example.com', name: 'Olivia' },
        dishes: ['Pad Thai', 'Spring Rolls', 'Mango Sticky Rice'],
        tableNumber: 11,
        date: '2023-10-11',
    },
    {
        user: { email: 'william@example.com', name: 'William' },
        dishes: ['Steak', 'Mashed Potatoes', 'Asparagus'],
        tableNumber: 12,
        date: '2023-10-12',
    },
    {
        user: { email: 'ava@example.com', name: 'Ava' },
        dishes: ['Sushi', 'Edamame', 'Mochi'],
        tableNumber: 13,
        date: '2023-10-13',
    },
    {
        user: { email: 'liam@example.com', name: 'Liam' },
        dishes: ['Pizza', 'Caesar Salad', 'Brownie'],
        tableNumber: 14,
        date: '2023-10-14',
    },
    {
        user: { email: 'mia@example.com', name: 'Mia' },
        dishes: ['Burger', 'Onion Rings', 'Chocolate Shake'],
        tableNumber: 15,
        date: '2023-10-15',
    },
    {
        user: { email: 'noah@example.com', name: 'Noah' },
        dishes: ['Tacos', 'Nachos', 'Flan'],
        tableNumber: 16,
        date: '2023-10-16',
    },
    {
        user: { email: 'isabella@example.com', name: 'Isabella' },
        dishes: ['Pasta', 'Garlic Bread', 'Cheesecake'],
        tableNumber: 17,
        date: '2023-10-17',
    },
    {
        user: { email: 'sophia@example.com', name: 'Sophia' },
        dishes: ['Sushi', 'Tempura', 'Green Tea Ice Cream'],
        tableNumber: 18,
        date: '2023-10-18',
    },
    {
        user: { email: 'logan@example.com', name: 'Logan' },
        dishes: ['Steak', 'Fries', 'Chocolate Cake'],
        tableNumber: 19,
        date: '2023-10-19',
    },
    {
        user: { email: 'emily@example.com', name: 'Emily' },
        dishes: ['Ramen', 'Gyoza', 'Matcha Ice Cream'],
        tableNumber: 20,
        date: '2023-10-20',
    },
    {
        user: { email: 'benjamin@example.com', name: 'Benjamin' },
        dishes: ['Pad Thai', 'Spring Rolls', 'Mango Sticky Rice'],
        tableNumber: 21,
        date: '2023-10-21',
    },
    {
        user: { email: 'charlotte@example.com', name: 'Charlotte' },
        dishes: ['Fried Chicken', 'Mashed Potatoes', 'Coleslaw'],
        tableNumber: 22,
        date: '2023-10-22',
    },
    {
        user: { email: 'mason@example.com', name: 'Mason' },
        dishes: ['Burger', 'Fries', 'Milkshake'],
        tableNumber: 23,
        date: '2023-10-23',
    },
    {
        user: { email: 'amelia@example.com', name: 'Amelia' },
        dishes: ['Pizza', 'Garlic Bread', 'Ice Cream'],
        tableNumber: 24,
        date: '2023-10-24',
    },
    {
        user: { email: 'elijah@example.com', name: 'Elijah' },
        dishes: ['Sushi', 'Miso Soup', 'Green Tea Ice Cream'],
        tableNumber: 25,
        date: '2023-10-25',
    },
    {
        user: { email: 'harper@example.com', name: 'Harper' },
        dishes: ['Tacos', 'Guacamole', 'Churros'],
        tableNumber: 26,
        date: '2023-10-26',
    },
    {
        user: { email: 'ethan@example.com', name: 'Ethan' },
        dishes: ['Burger', 'Onion Rings', 'Chocolate Shake'],
        tableNumber: 27,
        date: '2023-10-27',
    },
    {
        user: { email: 'evelyn@example.com', name: 'Evelyn' },
        dishes: ['Pasta', 'Bruschetta', 'Tiramisu'],
        tableNumber: 28,
        date: '2023-10-28',
    },
    {
        user: { email: 'lucas@example.com', name: 'Lucas' },
        dishes: ['Steak', 'Mashed Potatoes', 'Asparagus'],
        tableNumber: 29,
        date: '2023-10-29',
    },
    {
        user: { email: 'abigail@example.com', name: 'Abigail' },
        dishes: ['Sushi', 'Edamame', 'Mochi'],
        tableNumber: 30,
        date: '2023-10-30',
    },
    {
        user: { email: 'alexander@example.com', name: 'Alexander' },
        dishes: ['Pizza', 'Caesar Salad', 'Brownie'],
        tableNumber: 31,
        date: '2023-10-31',
    },
    {
        user: { email: 'ella@example.com', name: 'Ella' },
        dishes: ['Burger', 'Fries', 'Milkshake'],
        tableNumber: 32,
        date: '2023-11-01',
    },
    {
        user: { email: 'jackson@example.com', name: 'Jackson' },
        dishes: ['Tacos', 'Nachos', 'Flan'],
        tableNumber: 33,
        date: '2023-11-02',
    },
    {
        user: { email: 'scarlett@example.com', name: 'Scarlett' },
        dishes: ['Pasta', 'Garlic Bread', 'Cheesecake'],
        tableNumber: 34,
        date: '2023-11-03',
    },
    {
        user: { email: 'aiden@example.com', name: 'Aiden' },
        dishes: ['Sushi', 'Tempura', 'Green Tea Ice Cream'],
        tableNumber: 35,
        date: '2023-11-04',
    },
    {
        user: { email: 'grace@example.com', name: 'Grace' },
        dishes: ['Steak', 'Fries', 'Chocolate Cake'],
        tableNumber: 36,
        date: '2023-11-05',
    },
    {
        user: { email: 'samuel@example.com', name: 'Samuel' },
        dishes: ['Ramen', 'Gyoza', 'Matcha Ice Cream'],
        tableNumber: 37,
        date: '2023-11-06',
    },
    {
        user: { email: 'chloe@example.com', name: 'Chloe' },
        dishes: ['Pad Thai', 'Spring Rolls', 'Mango Sticky Rice'],
        tableNumber: 38,
        date: '2023-11-07',
    },
    {
        user: { email: 'joseph@example.com', name: 'Joseph' },
        dishes: ['Fried Chicken', 'Mashed Potatoes', 'Coleslaw'],
        tableNumber: 39,
        date: '2023-11-08',
    },
    {
        user: { email: 'lily@example.com', name: 'Lily' },
        dishes: ['Burger', 'Onion Rings', 'Chocolate Shake'],
        tableNumber: 40,
        date: '2023-11-09',
    },
    {
        user: { email: 'daniel@example.com', name: 'Daniel' },
        dishes: ['Pizza', 'Garlic Bread', 'Ice Cream'],
        tableNumber: 41,
        date: '2023-11-10',
    },
    {
        user: { email: 'zoey@example.com', name: 'Zoey' },
        dishes: ['Sushi', 'Miso Soup', 'Green Tea Ice Cream'],
        tableNumber: 42,
        date: '2023-11-11',
    },
    {
        user: { email: 'matthew@example.com', name: 'Matthew' },
        dishes: ['Tacos', 'Guacamole', 'Churros'],
        tableNumber: 43,
        date: '2023-11-12',
    },
    {
        user: { email: 'hannah@example.com', name: 'Hannah' },
        dishes: ['Burger', 'Fries', 'Milkshake'],
        tableNumber: 44,
        date: '2023-11-13',
    },
    {
        user: { email: 'owen@example.com', name: 'Owen' },
        dishes: ['Pasta', 'Bruschetta', 'Tiramisu'],
        tableNumber: 45,
        date: '2023-11-14',
    },
    {
        user: { email: 'ella@example.com', name: 'Ella' },
        dishes: ['Steak', 'Mashed Potatoes', 'Asparagus'],
        tableNumber: 46,
        date: '2023-11-15',
    },
    {
        user: { email: 'nathan@example.com', name: 'Nathan' },
        dishes: ['Sushi', 'Edamame', 'Mochi'],
        tableNumber: 47,
        date: '2023-11-16',
    },
    {
        user: { email: 'lillian@example.com', name: 'Lillian' },
        dishes: ['Pizza', 'Caesar Salad', 'Brownie'],
        tableNumber: 48,
        date: '2023-11-17',
    },
    {
        user: { email: 'ryan@example.com', name: 'Ryan' },
        dishes: ['Burger', 'Fries', 'Milkshake'],
        tableNumber: 49,
        date: '2023-11-18',
    },
    {
        user: { email: 'layla@example.com', name: 'Layla' },
        dishes: ['Tacos', 'Nachos', 'Flan'],
        tableNumber: 50,
        date: '2023-11-19',
    },
    {
        user: { email: 'isaac@example.com', name: 'Isaac' },
        dishes: ['Pasta', 'Garlic Bread', 'Cheesecake'],
        tableNumber: 51,
        date: '2023-11-20',
    },
    {
        user: { email: 'zoey@example.com', name: 'Zoey' },
        dishes: ['Sushi', 'Tempura', 'Green Tea Ice Cream'],
        tableNumber: 52,
        date: '2023-11-21',
    },
    {
        user: { email: 'leo@example.com', name: 'Leo' },
        dishes: ['Steak', 'Fries', 'Chocolate Cake'],
        tableNumber: 53,
        date: '2023-11-22',
    },
    {
        user: { email: 'ella@example.com', name: 'Ella' },
        dishes: ['Ramen', 'Gyoza', 'Matcha Ice Cream'],
        tableNumber: 54,
        date: '2023-11-23',
    },
    {
        user: { email: 'luke@example.com', name: 'Luke' },
        dishes: ['Pad Thai', 'Spring Rolls', 'Mango Sticky Rice'],
        tableNumber: 55,
        date: '2023-11-24',
    },
];

export const overView3 = [
    {
        user: { email: 'john@example.com', name: 'John' },
        dishes: ['Caesar Salad', 'Naan', 'Cheesecake'],
        tableNumber: 1,
        date: '2023-10-01',
    },
    {
        user: { email: 'jane@example.com', name: 'Jane' },
        dishes: ['Grilled Salmon', 'Naan', 'Syrup'],
        tableNumber: 2,
        date: '2023-10-02',
    },
    {
        user: { email: 'alice@example.com', name: 'Alice' },
        dishes: ['Beef Steak', 'Burger', 'Steak Sandwich'],
        tableNumber: 3,
        date: '2023-10-03',
    },
    {
        user: { email: 'bob@example.com', name: 'Bob' },
        dishes: ['Pasta', 'Garlic Bread', 'Chocolate Cake'],
        tableNumber: 4,
        date: '2023-10-04',
    },
    {
        user: { email: 'charlie@example.com', name: 'Charlie' },
        dishes: ['Pizza', 'Pasta', 'Tiramisu'],
        tableNumber: 5,
        date: '2023-10-05',
    },
    {
        user: { email: 'david@example.com', name: 'David' },
        dishes: ['Sushi', 'Miso Soup', 'Green Tea'],
        tableNumber: 6,
        date: '2023-10-06',
    },
    {
        user: { email: 'emily@example.com', name: 'Emily' },
        dishes: ['Chicken Wings', 'Fries', 'Vanilla Pudding'],
        tableNumber: 7,
        date: '2023-10-07',
    },
    {
        user: { email: 'frank@example.com', name: 'Frank' },
        dishes: ['Beef Burger', 'Fries', 'Apple Pie'],
        tableNumber: 8,
        date: '2023-10-08',
    },
    {
        user: { email: 'grace@example.com', name: 'Grace' },
        dishes: ['Fried Rice', 'Spring Rolls', 'Mango Sticky Rice'],
        tableNumber: 9,
        date: '2023-10-09',
    },
    {
        user: { email: 'henry@example.com', name: 'Henry' },
        dishes: ['Grilled Chicken', 'Salad', 'Ice Cream'],
        tableNumber: 10,
        date: '2023-10-10',
    },
    {
        user: { email: 'irene@example.com', name: 'Irene' },
        dishes: ['Vegetable Stir Fry', 'Noodles', 'Fruit Salad'],
        tableNumber: 11,
        date: '2023-10-11',
    },
    {
        user: { email: 'jack@example.com', name: 'Jack' },
        dishes: ['Beef Steak', 'Potatoes', 'Brownie'],
        tableNumber: 12,
        date: '2023-10-12',
    },
    {
        user: { email: 'katie@example.com', name: 'Katie' },
        dishes: ['Seafood Pasta', 'Garlic Bread', 'Lemon Sorbet'],
        tableNumber: 13,
        date: '2023-10-13',
    },
    {
        user: { email: 'lucas@example.com', name: 'Lucas' },
        dishes: ['Chicken Caesar Salad', 'Garlic Bread', 'Cheesecake'],
        tableNumber: 14,
        date: '2023-10-14',
    },
    {
        user: { email: 'mona@example.com', name: 'Mona' },
        dishes: ['Tofu Stir Fry', 'Rice', 'Green Tea Cake'],
        tableNumber: 15,
        date: '2023-10-15',
    },
    {
        user: { email: 'nathan@example.com', name: 'Nathan' },
        dishes: ['Pasta Carbonara', 'Salad', 'Tiramisu'],
        tableNumber: 16,
        date: '2023-10-16',
    },
    {
        user: { email: 'olivia@example.com', name: 'Olivia' },
        dishes: ['Vegetable Curry', 'Naan', 'Raita'],
        tableNumber: 17,
        date: '2023-10-17',
    },
    {
        user: { email: 'peter@example.com', name: 'Peter' },
        dishes: ['Grilled Salmon', 'Asparagus', 'Apple Pie'],
        tableNumber: 18,
        date: '2023-10-18',
    },
    {
        user: { email: 'quincy@example.com', name: 'Quincy' },
        dishes: ['Pork Belly', 'Rice', 'Pineapple Sorbet'],
        tableNumber: 19,
        date: '2023-10-19',
    },
    {
        user: { email: 'rachel@example.com', name: 'Rachel' },
        dishes: ['Spaghetti', 'Garlic Bread', 'Chocolate Mousse'],
        tableNumber: 20,
        date: '2023-10-20',
    },
    {
        user: { email: 'sam@example.com', name: 'Sam' },
        dishes: ['Steak Frites', 'Caesar Salad', 'Crème Brûlée'],
        tableNumber: 21,
        date: '2023-10-21',
    },
    {
        user: { email: 'tina@example.com', name: 'Tina' },
        dishes: ['Lamb Chop', 'Potatoes', 'Mango Sorbet'],
        tableNumber: 22,
        date: '2023-10-22',
    },
    {
        user: { email: 'ursula@example.com', name: 'Ursula' },
        dishes: ['Fettuccine Alfredo', 'Salad', 'Panna Cotta'],
        tableNumber: 23,
        date: '2023-10-23',
    },
    {
        user: { email: 'victor@example.com', name: 'Victor' },
        dishes: ['Grilled Chicken', 'Potatoes', 'Chocolate Cake'],
        tableNumber: 24,
        date: '2023-10-24',
    },
    {
        user: { email: 'wendy@example.com', name: 'Wendy' },
        dishes: ['Eggplant Parmesan', 'Garlic Bread', 'Pistachio Ice Cream'],
        tableNumber: 25,
        date: '2023-10-25',
    },
    {
        user: { email: 'xander@example.com', name: 'Xander' },
        dishes: ['Seafood Paella', 'Fried Calamari', 'Churros'],
        tableNumber: 26,
        date: '2023-10-26',
    },
    {
        user: { email: 'yara@example.com', name: 'Yara' },
        dishes: ['Lobster Roll', 'Fries', 'Key Lime Pie'],
        tableNumber: 27,
        date: '2023-10-27',
    },
    {
        user: { email: 'zane@example.com', name: 'Zane' },
        dishes: ['Peking Duck', 'Spring Rolls', 'Green Tea Cake'],
        tableNumber: 28,
        date: '2023-10-28',
    },
    {
        user: { email: 'anna@example.com', name: 'Anna' },
        dishes: ['Spaghetti Bolognese', 'Garlic Bread', 'Tiramisu'],
        tableNumber: 29,
        date: '2023-10-29',
    },
    {
        user: { email: 'bella@example.com', name: 'Bella' },
        dishes: ['Fried Chicken', 'Mac and Cheese', 'Brownie'],
        tableNumber: 30,
        date: '2023-10-30',
    },
    {
        user: { email: 'claire@example.com', name: 'Claire' },
        dishes: ['Lamb Rack', 'Salad', 'Chocolate Mousse'],
        tableNumber: 31,
        date: '2023-10-31',
    },
    {
        user: { email: 'daniel@example.com', name: 'Daniel' },
        dishes: ['Grilled Fish', 'Rice', 'Peach Sorbet'],
        tableNumber: 32,
        date: '2023-11-01',
    },
    {
        user: { email: 'ellen@example.com', name: 'Ellen' },
        dishes: ['Vegetable Tacos', 'Chips', 'Lemon Sorbet'],
        tableNumber: 33,
        date: '2023-11-02',
    },
    {
        user: { email: 'finn@example.com', name: 'Finn' },
        dishes: ['Chicken Schnitzel', 'Potatoes', 'Apple Strudel'],
        tableNumber: 34,
        date: '2023-11-03',
    },
    {
        user: { email: 'grayson@example.com', name: 'Grayson' },
        dishes: ['Burger', 'Fries', 'Chocolate Cake'],
        tableNumber: 35,
        date: '2023-11-04',
    },
    {
        user: { email: 'harry@example.com', name: 'Harry' },
        dishes: ['Lasagna', 'Garlic Bread', 'Tiramisu'],
        tableNumber: 36,
        date: '2023-11-05',
    },
    {
        user: { email: 'isla@example.com', name: 'Isla' },
        dishes: ['Veggie Wrap', 'Chips', 'Fruit Salad'],
        tableNumber: 37,
        date: '2023-11-06',
    },
    {
        user: { email: 'joseph@example.com', name: 'Joseph' },
        dishes: ['Beef Stir Fry', 'Rice', 'Mango Sorbet'],
        tableNumber: 38,
        date: '2023-11-07',
    },
    {
        user: { email: 'kevin@example.com', name: 'Kevin' },
        dishes: ['BBQ Ribs', 'Fries', 'Lemon Sorbet'],
        tableNumber: 39,
        date: '2023-11-08',
    },
    {
        user: { email: 'lily@example.com', name: 'Lily' },
        dishes: ['Vegetarian Pizza', 'Garlic Bread', 'Vanilla Ice Cream'],
        tableNumber: 40,
        date: '2023-11-09',
    },
    {
        user: { email: 'mike@example.com', name: 'Mike' },
        dishes: ['Chicken Shawarma', 'Rice', 'Baklava'],
        tableNumber: 41,
        date: '2023-11-10',
    },
    {
        user: { email: 'nora@example.com', name: 'Nora' },
        dishes: ['Grilled Shrimp', 'Salad', 'Chocolate Pudding'],
        tableNumber: 42,
        date: '2023-11-11',
    },
    {
        user: { email: 'olga@example.com', name: 'Olga' },
        dishes: ['Pasta Primavera', 'Garlic Bread', 'Cheesecake'],
        tableNumber: 43,
        date: '2023-11-12',
    },
    {
        user: { email: 'penny@example.com', name: 'Penny' },
        dishes: ['Falafel', 'Hummus', 'Baklava'],
        tableNumber: 44,
        date: '2023-11-13',
    },
    {
        user: { email: 'quinn@example.com', name: 'Quinn' },
        dishes: ['Chicken Alfredo', 'Garlic Bread', 'Lemon Sorbet'],
        tableNumber: 45,
        date: '2023-11-14',
    },
    {
        user: { email: 'rose@example.com', name: 'Rose' },
        dishes: ['Veggie Burger', 'Sweet Potato Fries', 'Apple Pie'],
        tableNumber: 46,
        date: '2023-11-15',
    },
    {
        user: { email: 'steve@example.com', name: 'Steve' },
        dishes: ['Fried Chicken', 'Mac and Cheese', 'Pecan Pie'],
        tableNumber: 47,
        date: '2023-11-16',
    },
    {
        user: { email: 'tina@example.com', name: 'Tina' },
        dishes: ['Vegetable Soup', 'Salad', 'Cinnamon Roll'],
        tableNumber: 48,
        date: '2023-11-17',
    },
    {
        user: { email: 'ursula@example.com', name: 'Ursula' },
        dishes: ['Grilled Chicken', 'Steamed Vegetables', 'Panna Cotta'],
        tableNumber: 49,
        date: '2023-11-18',
    },
    {
        user: { email: 'vance@example.com', name: 'Vance' },
        dishes: ['Fish Tacos', 'Chips', 'Lemon Sorbet'],
        tableNumber: 50,
        date: '2023-11-19',
    },
    {
        user: { email: 'will@example.com', name: 'Will' },
        dishes: ['Pork Chop', 'Gravy', 'Peach Cobbler'],
        tableNumber: 51,
        date: '2023-11-20',
    },
    {
        user: { email: 'xander@example.com', name: 'Xander' },
        dishes: ['Steak', 'Mashed Potatoes', 'Apple Pie'],
        tableNumber: 52,
        date: '2023-11-21',
    },
    {
        user: { email: 'yasmine@example.com', name: 'Yasmine' },
        dishes: ['Chicken Kabob', 'Couscous', 'Date Cake'],
        tableNumber: 53,
        date: '2023-11-22',
    },
    {
        user: { email: 'zach@example.com', name: 'Zach' },
        dishes: ['Sushi', 'Rice', 'Mochi'],
        tableNumber: 54,
        date: '2023-11-23',
    },
    {
        user: { email: 'amanda@example.com', name: 'Amanda' },
        dishes: ['Tacos', 'Guacamole', 'Flan'],
        tableNumber: 55,
        date: '2023-11-24',
    },
];
