export const overView = [
    {
        user: { email: 'john@example.com', name: 'John' },
        dishes: ['Caesar Salad', 'Naan', 'Cheesecake'],
        tableNumber: 1,
        date: '2023-10-01',
    },
    {
        user: { email: 'jane@example.com', name: 'Jane' },
        dishes: ['Grilled Salmon', 'Naan', 'Pancakes', 'Syrup'],
        tableNumber: 2,
        date: '2023-10-02',
    },
    {
        user: { email: 'alice@example.com', name: 'Alice' },
        dishes: ['Beef Steak', 'Burger', 'Steak Sandwich'],
        tableNumber: 3,
        date: '2023-10-03',
    },
    {
        user: { email: 'bob@example.com', name: 'Bob' },
        dishes: ['Caesar Salad', 'Grilled Salmon', 'Pancakes', 'Syrup'],
        tableNumber: 4,
        date: '2023-10-04',
    },
    {
        user: { email: 'charlie@example.com', name: 'Charlie' },
        dishes: ['Naan', 'Burger', 'Cheesecake'],
        tableNumber: 5,
        date: '2023-10-05',
    },
    {
        user: { email: 'emma@example.com', name: 'Emma' },
        dishes: ['Caesar Salad'],
        tableNumber: 6,
        date: '2023-10-06',
    },
    {
        user: { email: 'michael@example.com', name: 'Michael' },
        dishes: ['Grilled Salmon', 'Beef Steak'],
        tableNumber: 7,
        date: '2023-10-07',
    },
    {
        user: { email: 'sophia@example.com', name: 'Sophia' },
        dishes: ['Burger', 'Naan', 'Steak Sandwich'],
        tableNumber: 8,
        date: '2023-10-08',
    },
    {
        user: { email: 'william@example.com', name: 'William' },
        dishes: ['Sushi', 'Naan', 'Burrito'],
        tableNumber: 9,
        date: '2023-10-09',
    },
    {
        user: { email: 'olivia@example.com', name: 'Olivia' },
        dishes: ['Caesar Salad', 'Burrito', 'Cheesecake'],
        tableNumber: 10,
        date: '2023-10-10',
    },
    {
        user: { email: 'james@example.com', name: 'James' },
        dishes: ['Grilled Salmon', 'Naan', 'Ramen', 'Cheesecake'],
        tableNumber: 11,
        date: '2023-10-11',
    },
    {
        user: { email: 'amelia@example.com', name: 'Amelia' },
        dishes: ['Beef Steak', 'Burger'],
        tableNumber: 12,
        date: '2023-10-12',
    },
    {
        user: { email: 'benjamin@example.com', name: 'Benjamin' },
        dishes: ['Caesar Salad', 'Naan', 'Ramen'],
        tableNumber: 13,
        date: '2023-10-13',
    },
    {
        user: { email: 'mia@example.com', name: 'Mia' },
        dishes: ['Sushi', 'Caesar Salad'],
        tableNumber: 14,
        date: '2023-10-14',
    },
    {
        user: { email: 'ethan@example.com', name: 'Ethan' },
        dishes: ['Grilled Salmon', 'Beef Steak', 'Ramen'],
        tableNumber: 15,
        date: '2023-10-15',
    },
];
