export const feedback = [
    {
        name: 'Alice Johnson',
        email: 'alice.johnson@example.com',
        dish: 'Pasta Primavera',
        rating: 5,
        feedback: 'Absolutely delicious, will order again!',
        date: '2025-01-10',
    },
    {
        name: 'Bob Smith',
        email: 'bob.smith@example.com',
        dish: 'Chicken Alfredo',
        rating: 4,
        feedback: 'Great taste but a little too creamy for my liking.',
        date: '2025-01-12',
    },
    {
        name: 'Charlie Lee',
        email: 'charlie.lee@example.com',
        dish: 'Vegetable Stir Fry',
        rating: 3,
        feedback: 'It was okay, but could use more seasoning.',
        date: '2025-01-14',
    },
    {
        name: 'Diana Williams',
        email: 'diana.williams@example.com',
        dish: 'Margherita Pizza',
        rating: 5,
        feedback: 'Perfectly cooked, loved the fresh basil!',
        date: '2025-01-15',
    },
    {
        name: 'Ethan Harris',
        email: 'ethan.harris@example.com',
        dish: 'Caesar Salad',
        rating: 4,
        feedback: 'Fresh ingredients, but the dressing was a bit too salty.',
        date: '2025-01-18',
    },
    {
        name: 'Fay Clark',
        email: 'fay.clark@example.com',
        dish: 'Spaghetti Bolognese',
        rating: 4,
        feedback: 'Rich flavor, but could be a bit spicier.',
        date: '2025-01-20',
    },
    {
        name: 'George Young',
        email: 'george.young@example.com',
        dish: 'Grilled Salmon',
        rating: 5,
        feedback: 'Perfectly grilled, very tender and tasty!',
        date: '2025-01-21',
    },
    {
        name: 'Hannah Davis',
        email: 'hannah.davis@example.com',
        dish: 'Beef Tacos',
        rating: 2,
        feedback: 'The beef was too dry and bland.',
        date: '2025-01-22',
    },
    {
        name: 'Bob Smith',
        email: 'bob.smith@example.com',
        dish: 'Pasta Primavera',
        rating: 5,
        feedback: "Very tasty, one of the best pastas I've had!",
        date: '2025-01-11',
    },
    {
        name: 'Charlie Brown',
        email: 'charlie.brown@example.com',
        dish: 'Pasta Primavera',
        rating: 5,
        feedback: 'Perfectly cooked, the sauce was just right.',
        date: '2025-01-12',
    },
    {
        name: 'David Lee',
        email: 'david.lee@example.com',
        dish: 'Pasta Primavera',
        rating: 5,
        feedback: 'Great flavor, highly recommend this dish.',
        date: '2025-01-13',
    },
    {
        name: 'Emma Davis',
        email: 'emma.davis@example.com',
        dish: 'Pasta Primavera',
        rating: 5,
        feedback: 'Loved the creamy texture, definitely ordering again.',
        date: '2025-01-14',
    },

    {
        name: 'Ivy Taylor',
        email: 'ivy.taylor@example.com',
        dish: 'Chicken Nuggets',
        rating: 3,
        feedback: 'A bit overcooked, but the dipping sauces were good.',
        date: '2025-01-25',
    },
    {
        name: 'Jack Roberts',
        email: 'jack.roberts@example.com',
        dish: 'Fried Rice',
        rating: 4,
        feedback: 'Tasty and filling, but could have used more vegetables.',
        date: '2025-01-28',
    },
    {
        name: 'Kara Moore',
        email: 'kara.moore@example.com',
        dish: 'Lasagna',
        rating: 5,
        feedback: "One of the best lasagnas I've ever had!",
        date: '2025-01-30',
    },
    {
        name: 'Liam Scott',
        email: 'liam.scott@example.com',
        dish: 'BBQ Ribs',
        rating: 5,
        feedback: 'Ribs were tender, full of flavor, and perfectly cooked.',
        date: '2025-01-11',
    },
    {
        name: 'Megan Carter',
        email: 'megan.carter@example.com',
        dish: 'Chicken Tikka Masala',
        rating: 4,
        feedback: 'Spicy and flavorful, but a little too much sauce.',
        date: '2025-01-13',
    },
    {
        name: 'Nathan Evans',
        email: 'nathan.evans@example.com',
        dish: 'Fish and Chips',
        rating: 4,
        feedback: 'Crispy and light, but the fish was a bit too salty.',
        date: '2025-01-16',
    },
    {
        name: 'Olivia King',
        email: 'olivia.king@example.com',
        dish: 'Eggplant Parmesan',
        rating: 3,
        feedback: 'Decent, but the eggplant could have been cooked longer.',
        date: '2025-01-17',
    },
    {
        name: 'Paul Harris',
        email: 'paul.harris@example.com',
        dish: 'Beef Burger',
        rating: 5,
        feedback: 'Juicy and delicious, exactly how I like it.',
        date: '2025-01-19',
    },
    {
        name: 'Quinn Hill',
        email: 'quinn.hill@example.com',
        dish: 'Sushi Rolls',
        rating: 3,
        feedback: 'Not bad, but the rice was a bit too sticky for my taste.',
        date: '2025-01-23',
    },
    {
        name: 'Rachel Green',
        email: 'rachel.green@example.com',
        dish: 'Vegetarian Burger',
        rating: 2,
        feedback: "Bland and unseasoned, didn't enjoy it.",
        date: '2025-01-24',
    },
    {
        name: 'Sam White',
        email: 'sam.white@example.com',
        dish: 'Peking Duck',
        rating: 5,
        feedback: 'Amazing flavors, crispy skin, highly recommended.',
        date: '2025-01-26',
    },

    {
        name: 'Anna Parker',
        email: 'anna.parker@example.com',
        dish: 'Mushroom Soup',
        rating: 2,
        feedback: 'The soup was too bland and watery.',
        date: '2025-01-30',
    },
    {
        name: 'Brandon Miller',
        email: 'brandon.miller@example.com',
        dish: 'Beef Steak',
        rating: 1,
        feedback: 'The steak was undercooked and tough.',
        date: '2025-01-29',
    },
    {
        name: 'Clara Lewis',
        email: 'clara.lewis@example.com',
        dish: 'Chicken Wings',
        rating: 2,
        feedback: 'Too greasy and lacked seasoning.',
        date: '2025-01-28',
    },
    {
        name: 'David Johnson',
        email: 'david.johnson@example.com',
        dish: 'Fried Shrimp',
        rating: 1,
        feedback: 'Shrimp was rubbery and not fresh.',
        date: '2025-01-27',
    },
    {
        name: 'Ella Thompson',
        email: 'ella.thompson@example.com',
        dish: 'Pork Ribs',
        rating: 2,
        feedback: 'The ribs were too tough and lacked flavor.',
        date: '2025-01-26',
    },
    {
        name: 'Frank Black',
        email: 'frank.black@example.com',
        dish: 'Vegetable Soup',
        rating: 2,
        feedback: 'The soup was bland, could use more spices.',
        date: '2025-01-25',
    },
    {
        name: 'Grace Harris',
        email: 'grace.harris@example.com',
        dish: 'Salmon Salad',
        rating: 2,
        feedback: 'The salmon was dry and the salad lacked dressing.',
        date: '2025-01-24',
    },
    {
        name: 'Henry Scott',
        email: 'henry.scott@example.com',
        dish: 'Cheese Pizza',
        rating: 1,
        feedback: 'The crust was soggy and the cheese was bland.',
        date: '2025-01-23',
    },
    {
        name: 'Sophia Williams',
        email: 'sophia.williams@example.com',
        dish: 'Fried Shrimp',
        rating: 1,
        feedback: 'The shrimp were overcooked and bland.',
        date: '2025-01-28',
    },
    {
        name: 'Lucas Martinez',
        email: 'lucas.martinez@example.com',
        dish: 'Fried Shrimp',
        rating: 1,
        feedback: 'Very disappointing, tasted stale.',
        date: '2025-01-29',
    },
    {
        name: 'Olivia Taylor',
        email: 'olivia.taylor@example.com',
        dish: 'Fried Shrimp',
        rating: 1,
        feedback: 'Shrimp was soggy and lacked flavor.',
        date: '2025-01-30',
    },
    {
        name: 'Ethan Harris',
        email: 'ethan.harris@example.com',
        dish: 'Fried Shrimp',
        rating: 1,
        feedback: 'Terrible, the shrimp were cold and greasy.',
        date: '2025-01-31',
    },
    {
        name: 'Mia Clark',
        email: 'mia.clark@example.com',
        dish: 'Fried Shrimp',
        rating: 1,
        feedback: 'Shrimp was undercooked and not crispy at all.',
        date: '2025-02-01',
    },
    {
        name: 'Benjamin Lewis',
        email: 'benjamin.lewis@example.com',
        dish: 'Fried Shrimp',
        rating: 1,
        feedback: "Worst fried shrimp I've ever had, no seasoning.",
        date: '2025-02-02',
    },
    {
        name: 'Isabelle Green',
        email: 'isabelle.green@example.com',
        dish: 'Beef Tacos',
        rating: 1,
        feedback: 'The beef was undercooked and unseasoned.',
        date: '2025-01-22',
    },
    {
        name: 'James Miller',
        email: 'james.miller@example.com',
        dish: 'Pasta Carbonara',
        rating: 2,
        feedback: 'The pasta was overcooked and the sauce too runny.',
        date: '2025-01-21',
    },
    {
        name: 'Kyle Foster',
        email: 'kyle.foster@example.com',
        dish: 'Chicken Parmesan',
        rating: 4,
        feedback: 'Crispy chicken and flavorful sauce.',
        date: '2025-01-20',
    },
    {
        name: 'Laura Mitchell',
        email: 'laura.mitchell@example.com',
        dish: 'Grilled Veggie Burger',
        rating: 4,
        feedback: 'Delicious and healthy, loved the grilled flavor.',
        date: '2025-01-19',
    },
    {
        name: 'Mike Davis',
        email: 'mike.davis@example.com',
        dish: 'Beef Wellington',
        rating: 5,
        feedback: 'Incredible dish, the beef was cooked perfectly.',
        date: '2025-01-18',
    },
    {
        name: 'John Doe',
        email: 'john.doe@example.com',
        dish: 'Pasta Primavera',
        rating: 4,
        feedback: 'Very good, but could use a bit more seasoning.',
        date: '2025-01-15',
    },
    {
        name: 'Emma Smith',
        email: 'emma.smith@example.com',
        dish: 'Pasta Primavera',
        rating: 4,
        feedback: 'Tasty, but the portion size was a little small.',
        date: '2025-01-18',
    },
    {
        name: 'Michael Brown',
        email: 'michael.brown@example.com',
        dish: 'Pasta Primavera',
        rating: 4,
        feedback:
            'The pasta was perfectly cooked, but the sauce was a bit too creamy.',
        date: '2025-01-20',
    },
    {
        name: 'Charlotte Davis',
        email: 'charlotte.davis@example.com',
        dish: 'Pasta Primavera',
        rating: 4,
        feedback:
            'Good dish, but a little more vegetables would have been great.',
        date: '2025-01-22',
    },
    {
        name: 'James Wilson',
        email: 'james.wilson@example.com',
        dish: 'Pasta Primavera',
        rating: 4,
        feedback:
            'Really enjoyed it, though the sauce could have been lighter.',
        date: '2025-01-25',
    },
    {
        name: 'Ava Thomas',
        email: 'ava.thomas@example.com',
        dish: 'Pasta Primavera',
        rating: 4,
        feedback:
            'A very nice dish, but I wish the flavor was a little more bold.',
        date: '2025-01-28',
    },
    {
        name: 'Nancy Allen',
        email: 'nancy.allen@example.com',
        dish: 'Shrimp Scampi',
        rating: 4,
        feedback: 'The shrimp was perfectly cooked, and the sauce was rich.',
        date: '2025-01-17',
    },
    {
        name: 'Oliver Carter',
        email: 'oliver.carter@example.com',
        dish: 'Vegetarian Burrito',
        rating: 4,
        feedback: 'Full of flavor and really filling!',
        date: '2025-01-16',
    },
    {
        name: 'Penny Clark',
        email: 'penny.clark@example.com',
        dish: 'Lamb Chops',
        rating: 5,
        feedback: 'Melt-in-your-mouth tenderness and great flavor.',
        date: '2025-01-15',
    },
    {
        name: 'Quincy White',
        email: 'quincy.white@example.com',
        dish: 'Grilled Chicken Salad',
        rating: 4,
        feedback: 'Light, fresh, and tasty.',
        date: '2025-01-14',
    },
    {
        name: 'Sophia Williams',
        email: 'sophia.williams@example.com',
        dish: 'Fried Shrimp',
        rating: 1,
        feedback: 'The shrimp was overcooked and lacked flavor.',
        date: '2025-01-28',
    },
    {
        name: 'Liam Jackson',
        email: 'liam.jackson@example.com',
        dish: 'Fried Shrimp',
        rating: 1,
        feedback: 'The shrimp was too salty and chewy, not enjoyable.',
        date: '2025-01-29',
    },
    {
        name: 'Rebecca King',
        email: 'rebecca.king@example.com',
        dish: 'Steak Frites',
        rating: 4,
        feedback: 'Great steak with crispy fries, a classic.',
        date: '2025-01-13',
    },
    {
        name: 'Steve Perez',
        email: 'steve.perez@example.com',
        dish: 'Chicken Tacos',
        rating: 5,
        feedback: 'Juicy chicken with a perfect balance of spices.',
        date: '2025-01-12',
    },
    {
        name: 'Tina Moore',
        email: 'tina.moore@example.com',
        dish: 'Cheeseburger',
        rating: 4,
        feedback: 'A solid cheeseburger with all the right toppings.',
        date: '2025-01-11',
    },
];
